# Generated by Django 4.0 on 2021-12-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='data',
            field=models.JSONField(),
        ),
    ]
